### ISSUE TITLE
Can't Merge a Pull Request

### ISSUE THREAD

**Issue by parkr** [octokit/go-octokit#81]
Hi. I was trying to move off of octokit.rb onto this, but it appears it's very incomplete. I tried to work around it by creating my own client and trying to create requests and do all this and it didn't work due to unexported fields in `Request`. Obviously I can write the HTTP requests in Go's native `net/http` package, but it'd be nice to have a package like this that makes things easier.

Is this project still underway?

**Comment by jingweno** [comment]
> but it appears it's very incomplete...Is this project still underway?

Yes. Some history: `go-octokit` was originally designed to power [gh](https://github.com/jingweno/gh) now [hub](https://github.com/github/hub), so only minimum APIs were implemented catering to their use cases. We have a command `gh-merge`/`hub-merge` but we [didn't use the merge API](https://github.com/github/hub/blob/master/commands/merge.go), hence this gap. I do hope to make `go-octokit` as a complete client and plan to come back to this project once I'm more free up from [the `gh` to `hub` migration](https://github.com/github/hub/issues/475). I also know @pengwynn is getting help from various excellent contributors currently to add more endpoints.

**Comment by pengwynn** [comment]
@parkr Patches are definitely welcome. :grinning: 

/cc #82

**Comment by parkr** [comment]
Before I go submitting PR's, one more question :)

Are there limitations in Google's implementation? Why not just use this? https://github.com/google/go-github
